
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ConstructionProgress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ConstructionProgress
 * 
 */
export type ConstructionProgressModel = runtime.Types.Result.DefaultSelection<Prisma.$ConstructionProgressPayload>

export type AggregateConstructionProgress = {
  _count: ConstructionProgressCountAggregateOutputType | null
  _avg: ConstructionProgressAvgAggregateOutputType | null
  _sum: ConstructionProgressSumAggregateOutputType | null
  _min: ConstructionProgressMinAggregateOutputType | null
  _max: ConstructionProgressMaxAggregateOutputType | null
}

export type ConstructionProgressAvgAggregateOutputType = {
  amount: number | null
}

export type ConstructionProgressSumAggregateOutputType = {
  amount: number | null
}

export type ConstructionProgressMinAggregateOutputType = {
  id: string | null
  date: Date | null
  amount: number | null
}

export type ConstructionProgressMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  amount: number | null
}

export type ConstructionProgressCountAggregateOutputType = {
  id: number
  date: number
  amount: number
  _all: number
}


export type ConstructionProgressAvgAggregateInputType = {
  amount?: true
}

export type ConstructionProgressSumAggregateInputType = {
  amount?: true
}

export type ConstructionProgressMinAggregateInputType = {
  id?: true
  date?: true
  amount?: true
}

export type ConstructionProgressMaxAggregateInputType = {
  id?: true
  date?: true
  amount?: true
}

export type ConstructionProgressCountAggregateInputType = {
  id?: true
  date?: true
  amount?: true
  _all?: true
}

export type ConstructionProgressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConstructionProgress to aggregate.
   */
  where?: Prisma.ConstructionProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConstructionProgresses to fetch.
   */
  orderBy?: Prisma.ConstructionProgressOrderByWithRelationInput | Prisma.ConstructionProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConstructionProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConstructionProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConstructionProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ConstructionProgresses
  **/
  _count?: true | ConstructionProgressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ConstructionProgressAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ConstructionProgressSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConstructionProgressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConstructionProgressMaxAggregateInputType
}

export type GetConstructionProgressAggregateType<T extends ConstructionProgressAggregateArgs> = {
      [P in keyof T & keyof AggregateConstructionProgress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConstructionProgress[P]>
    : Prisma.GetScalarType<T[P], AggregateConstructionProgress[P]>
}




export type ConstructionProgressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConstructionProgressWhereInput
  orderBy?: Prisma.ConstructionProgressOrderByWithAggregationInput | Prisma.ConstructionProgressOrderByWithAggregationInput[]
  by: Prisma.ConstructionProgressScalarFieldEnum[] | Prisma.ConstructionProgressScalarFieldEnum
  having?: Prisma.ConstructionProgressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConstructionProgressCountAggregateInputType | true
  _avg?: ConstructionProgressAvgAggregateInputType
  _sum?: ConstructionProgressSumAggregateInputType
  _min?: ConstructionProgressMinAggregateInputType
  _max?: ConstructionProgressMaxAggregateInputType
}

export type ConstructionProgressGroupByOutputType = {
  id: string
  date: Date
  amount: number
  _count: ConstructionProgressCountAggregateOutputType | null
  _avg: ConstructionProgressAvgAggregateOutputType | null
  _sum: ConstructionProgressSumAggregateOutputType | null
  _min: ConstructionProgressMinAggregateOutputType | null
  _max: ConstructionProgressMaxAggregateOutputType | null
}

type GetConstructionProgressGroupByPayload<T extends ConstructionProgressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConstructionProgressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConstructionProgressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConstructionProgressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConstructionProgressGroupByOutputType[P]>
      }
    >
  >



export type ConstructionProgressWhereInput = {
  AND?: Prisma.ConstructionProgressWhereInput | Prisma.ConstructionProgressWhereInput[]
  OR?: Prisma.ConstructionProgressWhereInput[]
  NOT?: Prisma.ConstructionProgressWhereInput | Prisma.ConstructionProgressWhereInput[]
  id?: Prisma.StringFilter<"ConstructionProgress"> | string
  date?: Prisma.DateTimeFilter<"ConstructionProgress"> | Date | string
  amount?: Prisma.FloatFilter<"ConstructionProgress"> | number
}

export type ConstructionProgressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type ConstructionProgressWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ConstructionProgressWhereInput | Prisma.ConstructionProgressWhereInput[]
  OR?: Prisma.ConstructionProgressWhereInput[]
  NOT?: Prisma.ConstructionProgressWhereInput | Prisma.ConstructionProgressWhereInput[]
  date?: Prisma.DateTimeFilter<"ConstructionProgress"> | Date | string
  amount?: Prisma.FloatFilter<"ConstructionProgress"> | number
}, "id">

export type ConstructionProgressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  _count?: Prisma.ConstructionProgressCountOrderByAggregateInput
  _avg?: Prisma.ConstructionProgressAvgOrderByAggregateInput
  _max?: Prisma.ConstructionProgressMaxOrderByAggregateInput
  _min?: Prisma.ConstructionProgressMinOrderByAggregateInput
  _sum?: Prisma.ConstructionProgressSumOrderByAggregateInput
}

export type ConstructionProgressScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConstructionProgressScalarWhereWithAggregatesInput | Prisma.ConstructionProgressScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConstructionProgressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConstructionProgressScalarWhereWithAggregatesInput | Prisma.ConstructionProgressScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ConstructionProgress"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"ConstructionProgress"> | Date | string
  amount?: Prisma.FloatWithAggregatesFilter<"ConstructionProgress"> | number
}

export type ConstructionProgressCreateInput = {
  id?: string
  date: Date | string
  amount: number
}

export type ConstructionProgressUncheckedCreateInput = {
  id?: string
  date: Date | string
  amount: number
}

export type ConstructionProgressUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ConstructionProgressUncheckedUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ConstructionProgressCreateManyInput = {
  id?: string
  date: Date | string
  amount: number
}

export type ConstructionProgressUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ConstructionProgressUncheckedUpdateManyInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ConstructionProgressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type ConstructionProgressAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type ConstructionProgressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type ConstructionProgressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type ConstructionProgressSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}



export type ConstructionProgressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  amount?: boolean
}, ExtArgs["result"]["constructionProgress"]>



export type ConstructionProgressSelectScalar = {
  id?: boolean
  date?: boolean
  amount?: boolean
}

export type ConstructionProgressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "amount", ExtArgs["result"]["constructionProgress"]>

export type $ConstructionProgressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ConstructionProgress"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    amount: number
  }, ExtArgs["result"]["constructionProgress"]>
  composites: {}
}

export type ConstructionProgressGetPayload<S extends boolean | null | undefined | ConstructionProgressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload, S>

export type ConstructionProgressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConstructionProgressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConstructionProgressCountAggregateInputType | true
  }

export interface ConstructionProgressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ConstructionProgress'], meta: { name: 'ConstructionProgress' } }
  /**
   * Find zero or one ConstructionProgress that matches the filter.
   * @param {ConstructionProgressFindUniqueArgs} args - Arguments to find a ConstructionProgress
   * @example
   * // Get one ConstructionProgress
   * const constructionProgress = await prisma.constructionProgress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConstructionProgressFindUniqueArgs>(args: Prisma.SelectSubset<T, ConstructionProgressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ConstructionProgress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConstructionProgressFindUniqueOrThrowArgs} args - Arguments to find a ConstructionProgress
   * @example
   * // Get one ConstructionProgress
   * const constructionProgress = await prisma.constructionProgress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConstructionProgressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConstructionProgressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConstructionProgress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressFindFirstArgs} args - Arguments to find a ConstructionProgress
   * @example
   * // Get one ConstructionProgress
   * const constructionProgress = await prisma.constructionProgress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConstructionProgressFindFirstArgs>(args?: Prisma.SelectSubset<T, ConstructionProgressFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConstructionProgress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressFindFirstOrThrowArgs} args - Arguments to find a ConstructionProgress
   * @example
   * // Get one ConstructionProgress
   * const constructionProgress = await prisma.constructionProgress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConstructionProgressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConstructionProgressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConstructionProgresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConstructionProgresses
   * const constructionProgresses = await prisma.constructionProgress.findMany()
   * 
   * // Get first 10 ConstructionProgresses
   * const constructionProgresses = await prisma.constructionProgress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const constructionProgressWithIdOnly = await prisma.constructionProgress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConstructionProgressFindManyArgs>(args?: Prisma.SelectSubset<T, ConstructionProgressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ConstructionProgress.
   * @param {ConstructionProgressCreateArgs} args - Arguments to create a ConstructionProgress.
   * @example
   * // Create one ConstructionProgress
   * const ConstructionProgress = await prisma.constructionProgress.create({
   *   data: {
   *     // ... data to create a ConstructionProgress
   *   }
   * })
   * 
   */
  create<T extends ConstructionProgressCreateArgs>(args: Prisma.SelectSubset<T, ConstructionProgressCreateArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ConstructionProgresses.
   * @param {ConstructionProgressCreateManyArgs} args - Arguments to create many ConstructionProgresses.
   * @example
   * // Create many ConstructionProgresses
   * const constructionProgress = await prisma.constructionProgress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConstructionProgressCreateManyArgs>(args?: Prisma.SelectSubset<T, ConstructionProgressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ConstructionProgress.
   * @param {ConstructionProgressDeleteArgs} args - Arguments to delete one ConstructionProgress.
   * @example
   * // Delete one ConstructionProgress
   * const ConstructionProgress = await prisma.constructionProgress.delete({
   *   where: {
   *     // ... filter to delete one ConstructionProgress
   *   }
   * })
   * 
   */
  delete<T extends ConstructionProgressDeleteArgs>(args: Prisma.SelectSubset<T, ConstructionProgressDeleteArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ConstructionProgress.
   * @param {ConstructionProgressUpdateArgs} args - Arguments to update one ConstructionProgress.
   * @example
   * // Update one ConstructionProgress
   * const constructionProgress = await prisma.constructionProgress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConstructionProgressUpdateArgs>(args: Prisma.SelectSubset<T, ConstructionProgressUpdateArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ConstructionProgresses.
   * @param {ConstructionProgressDeleteManyArgs} args - Arguments to filter ConstructionProgresses to delete.
   * @example
   * // Delete a few ConstructionProgresses
   * const { count } = await prisma.constructionProgress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConstructionProgressDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConstructionProgressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConstructionProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConstructionProgresses
   * const constructionProgress = await prisma.constructionProgress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConstructionProgressUpdateManyArgs>(args: Prisma.SelectSubset<T, ConstructionProgressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ConstructionProgress.
   * @param {ConstructionProgressUpsertArgs} args - Arguments to update or create a ConstructionProgress.
   * @example
   * // Update or create a ConstructionProgress
   * const constructionProgress = await prisma.constructionProgress.upsert({
   *   create: {
   *     // ... data to create a ConstructionProgress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConstructionProgress we want to update
   *   }
   * })
   */
  upsert<T extends ConstructionProgressUpsertArgs>(args: Prisma.SelectSubset<T, ConstructionProgressUpsertArgs<ExtArgs>>): Prisma.Prisma__ConstructionProgressClient<runtime.Types.Result.GetResult<Prisma.$ConstructionProgressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConstructionProgresses that matches the filter.
   * @param {ConstructionProgressFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const constructionProgress = await prisma.constructionProgress.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.ConstructionProgressFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a ConstructionProgress.
   * @param {ConstructionProgressAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const constructionProgress = await prisma.constructionProgress.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.ConstructionProgressAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of ConstructionProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressCountArgs} args - Arguments to filter ConstructionProgresses to count.
   * @example
   * // Count the number of ConstructionProgresses
   * const count = await prisma.constructionProgress.count({
   *   where: {
   *     // ... the filter for the ConstructionProgresses we want to count
   *   }
   * })
  **/
  count<T extends ConstructionProgressCountArgs>(
    args?: Prisma.Subset<T, ConstructionProgressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConstructionProgressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ConstructionProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConstructionProgressAggregateArgs>(args: Prisma.Subset<T, ConstructionProgressAggregateArgs>): Prisma.PrismaPromise<GetConstructionProgressAggregateType<T>>

  /**
   * Group by ConstructionProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConstructionProgressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConstructionProgressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConstructionProgressGroupByArgs['orderBy'] }
      : { orderBy?: ConstructionProgressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConstructionProgressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConstructionProgressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ConstructionProgress model
 */
readonly fields: ConstructionProgressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConstructionProgress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConstructionProgressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ConstructionProgress model
 */
export interface ConstructionProgressFieldRefs {
  readonly id: Prisma.FieldRef<"ConstructionProgress", 'String'>
  readonly date: Prisma.FieldRef<"ConstructionProgress", 'DateTime'>
  readonly amount: Prisma.FieldRef<"ConstructionProgress", 'Float'>
}
    

// Custom InputTypes
/**
 * ConstructionProgress findUnique
 */
export type ConstructionProgressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * Filter, which ConstructionProgress to fetch.
   */
  where: Prisma.ConstructionProgressWhereUniqueInput
}

/**
 * ConstructionProgress findUniqueOrThrow
 */
export type ConstructionProgressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * Filter, which ConstructionProgress to fetch.
   */
  where: Prisma.ConstructionProgressWhereUniqueInput
}

/**
 * ConstructionProgress findFirst
 */
export type ConstructionProgressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * Filter, which ConstructionProgress to fetch.
   */
  where?: Prisma.ConstructionProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConstructionProgresses to fetch.
   */
  orderBy?: Prisma.ConstructionProgressOrderByWithRelationInput | Prisma.ConstructionProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConstructionProgresses.
   */
  cursor?: Prisma.ConstructionProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConstructionProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConstructionProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConstructionProgresses.
   */
  distinct?: Prisma.ConstructionProgressScalarFieldEnum | Prisma.ConstructionProgressScalarFieldEnum[]
}

/**
 * ConstructionProgress findFirstOrThrow
 */
export type ConstructionProgressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * Filter, which ConstructionProgress to fetch.
   */
  where?: Prisma.ConstructionProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConstructionProgresses to fetch.
   */
  orderBy?: Prisma.ConstructionProgressOrderByWithRelationInput | Prisma.ConstructionProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConstructionProgresses.
   */
  cursor?: Prisma.ConstructionProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConstructionProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConstructionProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConstructionProgresses.
   */
  distinct?: Prisma.ConstructionProgressScalarFieldEnum | Prisma.ConstructionProgressScalarFieldEnum[]
}

/**
 * ConstructionProgress findMany
 */
export type ConstructionProgressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * Filter, which ConstructionProgresses to fetch.
   */
  where?: Prisma.ConstructionProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConstructionProgresses to fetch.
   */
  orderBy?: Prisma.ConstructionProgressOrderByWithRelationInput | Prisma.ConstructionProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ConstructionProgresses.
   */
  cursor?: Prisma.ConstructionProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConstructionProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConstructionProgresses.
   */
  skip?: number
  distinct?: Prisma.ConstructionProgressScalarFieldEnum | Prisma.ConstructionProgressScalarFieldEnum[]
}

/**
 * ConstructionProgress create
 */
export type ConstructionProgressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * The data needed to create a ConstructionProgress.
   */
  data: Prisma.XOR<Prisma.ConstructionProgressCreateInput, Prisma.ConstructionProgressUncheckedCreateInput>
}

/**
 * ConstructionProgress createMany
 */
export type ConstructionProgressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ConstructionProgresses.
   */
  data: Prisma.ConstructionProgressCreateManyInput | Prisma.ConstructionProgressCreateManyInput[]
}

/**
 * ConstructionProgress update
 */
export type ConstructionProgressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * The data needed to update a ConstructionProgress.
   */
  data: Prisma.XOR<Prisma.ConstructionProgressUpdateInput, Prisma.ConstructionProgressUncheckedUpdateInput>
  /**
   * Choose, which ConstructionProgress to update.
   */
  where: Prisma.ConstructionProgressWhereUniqueInput
}

/**
 * ConstructionProgress updateMany
 */
export type ConstructionProgressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ConstructionProgresses.
   */
  data: Prisma.XOR<Prisma.ConstructionProgressUpdateManyMutationInput, Prisma.ConstructionProgressUncheckedUpdateManyInput>
  /**
   * Filter which ConstructionProgresses to update
   */
  where?: Prisma.ConstructionProgressWhereInput
  /**
   * Limit how many ConstructionProgresses to update.
   */
  limit?: number
}

/**
 * ConstructionProgress upsert
 */
export type ConstructionProgressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * The filter to search for the ConstructionProgress to update in case it exists.
   */
  where: Prisma.ConstructionProgressWhereUniqueInput
  /**
   * In case the ConstructionProgress found by the `where` argument doesn't exist, create a new ConstructionProgress with this data.
   */
  create: Prisma.XOR<Prisma.ConstructionProgressCreateInput, Prisma.ConstructionProgressUncheckedCreateInput>
  /**
   * In case the ConstructionProgress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConstructionProgressUpdateInput, Prisma.ConstructionProgressUncheckedUpdateInput>
}

/**
 * ConstructionProgress delete
 */
export type ConstructionProgressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
  /**
   * Filter which ConstructionProgress to delete.
   */
  where: Prisma.ConstructionProgressWhereUniqueInput
}

/**
 * ConstructionProgress deleteMany
 */
export type ConstructionProgressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConstructionProgresses to delete
   */
  where?: Prisma.ConstructionProgressWhereInput
  /**
   * Limit how many ConstructionProgresses to delete.
   */
  limit?: number
}

/**
 * ConstructionProgress findRaw
 */
export type ConstructionProgressFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * ConstructionProgress aggregateRaw
 */
export type ConstructionProgressAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * ConstructionProgress without action
 */
export type ConstructionProgressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConstructionProgress
   */
  select?: Prisma.ConstructionProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConstructionProgress
   */
  omit?: Prisma.ConstructionProgressOmit<ExtArgs> | null
}
